name: ValueConverters.Avalonia Library

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 8.0.x

      - name: Setup Windows SDK
        uses: GuillaumeFalourd/setup-windows10-sdk-action@v1.5

      - name: Install dependencies
        run: dotnet restore ValueConverters.Avalonia\ValueConverters.Avalonia.csproj

      - name: Build
        run: dotnet build ValueConverters.Avalonia\ValueConverters.Avalonia.csproj --configuration Release --no-restore

      - name: Pack
        run: dotnet pack ValueConverters.Avalonia\ValueConverters.Avalonia.csproj -c Release --no-build -o .

      - name: Push NuGet package
        # run:  dotnet nuget push ".\*.nupkg" -k ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
        uses: actions/upload-artifact@v3
        with:
          name: nuget-packages
          path: ./*.nupkg
